[package]
name = "tinitime"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.59.0"
features = [
    "Graphics",
    "System",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
]
